<?php

namespace AppBundle\Repository;

/**
 * SoftInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
