<?php

namespace AppBundle\Repository;

/**
 * SoftReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftReportRepository extends \Doctrine\ORM\EntityRepository
{
}
