<?php

namespace AppBundle\Repository;

/**
 * SoftLeadsOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftLeadsOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
