<?php

namespace AppBundle\Repository;

/**
 * SoftMainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftMainRepository extends \Doctrine\ORM\EntityRepository
{

    public function getSoftMainByName($softmain)
    {
        $softmain = "%" . $softmain . "%";

        $qb = $this->createQueryBuilder('s')
            ->select('s.name')
            ->where('s.name LIKE :name')
            ->setParameter('name', $softmain)
            ->getQuery();
        return $qb->getResult();
    }
}
