<?php

namespace AppBundle\Repository;

/**
 * SoftSegmentOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftSegmentOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
