<?php

namespace AppBundle\Repository;

/**
 * SoftSocialMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftSocialMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
