<?php

namespace AppBundle\Repository;

/**
 * SoftOtherFunctionnalitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftOtherFunctionnalitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
