<?php

namespace AppBundle\Repository;

/**
 * SoftSeeAlsoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftSeeAlsoRepository extends \Doctrine\ORM\EntityRepository
{
}
