<?php

namespace AppBundle\Repository;

/**
 * SoftSupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftSupportRepository extends \Doctrine\ORM\EntityRepository
{

    public function searchInKnowledgeBaseLanguage($word)
    {
        $softsupport = "%" . $word . "%";

        $qb = $this->createQueryBuilder('s')
            ->where('s.knowledgeBaseLanguage LIKE :knowledgeBaseLanguage')
            ->setParameter('knowledgeBaseLanguage', $softsupport)
            ->getQuery();
        return $qb->getResult();
    }
}
