<?php

namespace AppBundle\Repository;

/**
 * SoftMarketingCampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftMarketingCampaignRepository extends \Doctrine\ORM\EntityRepository
{
}
