<?php

namespace AppBundle\Repository;

/**
 * SoftSupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftSupportRepository extends \Doctrine\ORM\EntityRepository
{
}
