<?php

namespace AppBundle\Repository;

/**
 * SoftContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftContactRepository extends \Doctrine\ORM\EntityRepository
{
}
