<?php

namespace AppBundle\Repository;

/**
 * SoftCommSupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftCommSupportRepository extends \Doctrine\ORM\EntityRepository
{
}
