<?php

namespace AppBundle\Repository;

/**
 * SoftwareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftwareRepository extends \Doctrine\ORM\EntityRepository
{
}
