<?php

namespace AppBundle\Repository;

/**
 * SoftOutboundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftOutboundRepository extends \Doctrine\ORM\EntityRepository
{
}
