<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchInTagName($word)
    {
        $tag = "%" . $word . "%";

        $qb = $this->createQueryBuilder('s')
            ->where('s.name LIKE :name')
            ->setParameter('name', $tag)
            ->getQuery();
        return $qb->getResult();
    }

    public function searchInTagDescription($word)
    {
        $tag = "%" . $word . "%";

        $qb = $this->createQueryBuilder('s')
            ->where('s.description LIKE :description')
            ->setParameter('description', $tag)
            ->getQuery();
        return $qb->getResult();
    }
}
