<?php

namespace AppBundle\Repository;

/**
 * VersusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersusRepository extends \Doctrine\ORM\EntityRepository
{
}
