<?php

namespace AppBundle\Repository;

/**
 * VersusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersusRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $soft1
     * @param $soft2
     * @return array
     * Find Good versus by names of softwares. Try 2 possibilities.
     *
     */
    public function findWithSoftNames($soft1, $soft2)
    {

        $qb = $this->createQueryBuilder('s')
            ->where('s.software1 = :soft1')
            ->andWhere('s.software2 = :soft2')
            ->setParameter('soft1', $soft1)
            ->setParameter('soft2', $soft2)
            ->getQuery();
        return $qb->getResult();
    }

    /**
     * @param $software
     * @return array
     *
     * Find versus where 1 software is concerned.
     *
     */
    public function findVersusByOneSoftware($software)
    {
        $qb = $this->createQueryBuilder('s')
            ->where('s.software1 = :soft1')
            ->orWhere('s.software2 = :soft1')
            ->setParameter('soft1', $software)
            ->getQuery();
        return $qb->getResult();

    }

}
