imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    logo_directory: '%kernel.root_dir%/../web/assets/img/logo'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
assetic:
  debug: '%kernel.debug%'
  use_controller: '%kernel.debug%'
  filters:
    cssrewrite: ~

easy_admin:
    site_name: 'Comparer.pro'

    entities:

        User:
            class: AppBundle\Entity\User
            form:
              fields:
                - username
                - { property: 'username', label: 'Nom du user' }
                - { property: 'email', label: 'E-mail', type: 'email', type_options: { trim: true } }
                - { property: 'plainPassword', type: 'repeated', type_options: { first_options: {label: 'Mot de passe'}, second_options: {label: 'Mot de passe à répéter'} } }

        Softwares:
            class: AppBundle\Entity\SoftMain
            form:
              fields:
                - name
                - { property: 'name', label: 'Nom du logiciel :' }
                - title
                - { property: 'title', label: 'Title (SEO) :' }
                - type
                - { property: 'type', label: 'Type de logiciel :' }
                - description
                - { property: 'description', label: 'Description :' }
                - comments
                - { property: 'comments', label: 'Commentaire neutre :' }
                - advantages
                - { property: 'advantages', label: 'Les avantages du logiciel :' }
                - drawbacks
                - { property: 'drawbacks', label: 'Les désavantages du logiciel :' }
                - tags
                - { property: 'tags', label: 'Les tags :', type_options: { 'by_reference': false }, allow_delete: true, allow_add: true, prototype: true  }
                - logo
                - { property: 'logo', label: 'logo en PNG :', type: 'file', type_options: {data_class: null} }
                - softInfo
                - { property: 'softInfo', label: 'Les infos principales :', type: 'AppBundle\Form\SoftInfoType', type_options: { data_class: 'AppBundle\Entity\SoftInfo', by_reference: true } }
                - softOutbound
                - { property: 'softOutbound', label: 'Canaux de communication sortants (outbound) :', type: 'AppBundle\Form\SoftOutboundType', type_options: { data_class: 'AppBundle\Entity\SoftOutbound', by_reference: true } }
                - softCommSupport
                - { property: 'softCommSupport', label: 'Support de Communication :', type: 'AppBundle\Form\SoftCommSupportType', type_options: { data_class: 'AppBundle\Entity\SoftCommSupport', by_reference: true } }
                - softLeadsOperation
                - { property: 'softLeadsOperation', label: 'Gestion des contacts :', type: 'AppBundle\Form\SoftLeadsOperationType', type_options: { data_class: 'AppBundle\Entity\SoftLeadsOperation', by_reference: true } }
                - softSegmentOperation
                - { property: 'softSegmentOperation', label: 'Gestion des segments :', type: 'AppBundle\Form\SoftSegmentOperationType', type_options: { data_class: 'AppBundle\Entity\SoftSegmentOperation', by_reference: true } }
                - softMarketingCampaign
                - { property: 'softMarketingCampaign', label: 'Campagnes marketing', type: 'AppBundle\Form\SoftMarketingCampaignType', type_options: { data_class: 'AppBundle\Entity\SoftMarketingCampaign', by_reference: true } }
                - softSocialMedia
                - { property: 'softSocialMedia', label: 'Intégration social média :', type: 'AppBundle\Form\SoftSocialMediaType', type_options: { data_class: 'AppBundle\Entity\SoftSocialMedia', by_reference: true } }
                - softReport
                - { property: 'softReport', label: 'Rapports :', type: 'AppBundle\Form\SoftReportType', type_options: { data_class: 'AppBundle\Entity\SoftReport', by_reference: true } }
                - softOtherFunctionnalities
                - { property: 'softOtherFunctionnalities', label: 'Autres fonctionnalités :', type: 'AppBundle\Form\SoftOtherFunctionnalitiesType', type_options: { data_class: 'AppBundle\Entity\SoftOtherFunctionnalities', by_reference: true } }
                - softSupport
                - { property: 'softSupport', label: 'Support client :', type: 'AppBundle\Form\SoftSupportType', type_options: { data_class: 'AppBundle\Entity\SoftSupport', by_reference: true } }
                - softContact
                - { property: 'softContact', label: 'Personne à contacter (non public) :', type: 'AppBundle\Form\SoftContactType', type_options: { data_class: 'AppBundle\Entity\SoftContact', by_reference: true } }
        Versus:
            class: AppBundle\Entity\Versus
        Tag:
            class: AppBundle\Entity\Tag
            form:
              fields:
                - name
                - { property: 'name', label: 'Nom :' }
                - title
                - { property: 'title', label: 'Title (SEO) :' }
                - description
                - { property: 'softMains', label: 'Liste des logiciels :', type_options: { by_reference: false }, allow_delete: true, allow_add: true, prototype: true }
